# Generated by Django 2.1.7 on 2019-02-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='datafile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
