# Generated by Django 2.1.7 on 2019-02-21 04:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190221_0655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='owner',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=36),
            preserve_default=False,
        ),
    ]
