# Generated by Django 2.1.7 on 2019-02-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190221_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='2019-02-21 04:06:44.539609+00:00')),
                ('json_field', models.TextField(max_length=3000, verbose_name='{"Parent Identifier":{"0":1001,"1":1010},"Student Identifier":{"0":1002,"1":1020}}')),
            ],
        ),
    ]
