# Generated by Django 2.1.7 on 2019-02-21 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_jsonmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsonmodel',
            name='json_field',
        ),
        migrations.RemoveField(
            model_name='jsonmodel',
            name='name',
        ),
    ]
