# Generated by Django 2.1.7 on 2019-02-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190221_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonmodel',
            name='json_field',
            field=models.TextField(default=12, max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jsonmodel',
            name='name',
            field=models.CharField(default=11, max_length=32),
            preserve_default=False,
        ),
    ]
