# Generated by Django 2.1.7 on 2019-02-21 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190221_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='created',
        ),
    ]
