# Generated by Django 2.1.7 on 2019-02-22 20:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_testupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsonmodel',
            name='json_field',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
